data:
    feature_columns: ['wb', 'wc', 'sigma8', 'ns', 'alpha_s', 'N_eff', 'w0', 'wa',
                        'sigma_logM', 'alpha', 'kappa', 'log10M1', 'log10_ng', 'r']
    label_columns: ['xi',]
    batch_size: 3040
    num_workers: 10
    shuffle: true
    train_data_path: "./emulator_data/sliced_r/TPCF_train.csv"
    val_data_path: "./emulator_data/sliced_r/TPCF_val.csv"
    test_data_path: "./emulator_data/sliced_r/TPCF_test.csv"
    feature_scaler: 'StandardLogScaler'
    label_scaler: 'StandardLogScaler'

model:
    type: FullyConnected
    hidden_dims: [512,512,512]
    activation: 'gelu'
    loss: 'L1Loss'
    dropout: 1.e-3
    learning_rate: 1.e-2
    weight_decay: 5.e-6
    batch_norm: false
    zero_bias: true
    scheduler_patience: 20

training:
    gpus: [0]
    max_epochs: 500
    stopping_patience: 50
    use_swa: false
    gamma: 0.97
    default_root_dir: "./emulator_data/emulators"
    log_save_dir: "emulator_logs"
