data:
    feature_columns: ['sigma_logM', 'alpha', 'kappa', 'log10M1', 'log10Mmin', 'r']
    label_columns: ['xi',]
    batch_size: 256
    num_workers: 10
    shuffle: true
    train_data_path: "./tpcf_data/TPCF_train.csv"
    val_data_path: "./tpcf_data/TPCF_val.csv"
    test_data_path: "./tpcf_data/TPCF_test.csv"
    feature_scaler: 'StandardScaler'
    label_scaler: 'StandardScaler'

model:
    hidden_dims: [128]
    activation: 'gelu'
    loss: 'L1Loss'
    dropout: 0.
    learning_rate: 1.e-2
    weight_decay: 5.e-6
    batch_norm: false
    type: FullyConnected

training:
    gpus: [0]
    max_epochs: 1500
    stochastic_weight_avg: true
    default_root_dir: "./emulators/"

